### ISSUE TITLE
Jquery AutoComplete Hides Back on the modal

### ISSUE THREAD

**Issue by tajeet** [jschr/bootstrap-modal#165]
If we have a auto complete on the modal. and when we search/type in anything in the text box. The return items get hidden behind the modal.

if i comment the following line in the modalmanager.js and replace that with the following it works fine( may be stacking modal on top of one another will not be working now) which is fine as I don't need that.
/\* This works fine
getIndexOfModal: function (modal) {
            for (var i = 0; i < this.stack.length; i++) {
                if (modal === this.stack[i]) return i;
            }
}

/\* this does not work */

getIndexOfModal: function (modal) {
         var index = 0;
         for (var i = 0; i < this.stack.length; i++) {
             if (this.stack[i].isShown) {
                 index++;
             }
         }
           /return index;
}

**Comment by ktheja** [comment]
.ui-autocomplete { z-index:2147483647; }  it is working in bootstrap modal also brother. Thank you very much.
