### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by bublikOff** [jschr/bootstrap-modal#203]
Ive two modals. The first one is long and the second is small. After I close the second body became scrollable. The 'modal-open' class removed from body despite that the first modal is remain opened.

To deal with it I had to add something like this
$modal.on('hidden', function() { $('body').toggleClass('modal-open-fix', $('.modal:visible').length > 0); });

**Comment by psyxx** [comment]
A follow up problem seems to have appeared. 
Here is the scenario:

1-On your demo Click View Demo For long modals
2-On the long modal click "Not so Long Modal"
3-On not so long modal click "Very Long modal"
4-Scroll down. Some of the content is missing. 

Looking at the source it seems that the  "not so long modal" button is not even loaded any more.
