### ISSUE TITLE
Not compatible with the latest BS 3.3.0 IE and FF it seems

### ISSUE THREAD

**Issue by emage** [jschr/bootstrap-modal#259]
I recently updated to the latest BS 3.3.0.  Still using the BS patch files, the following are what's happening:

in BS 3.3.0:
in Chrome browser:
"modal-scrollable" has a z-index of 2080
"modal-backdrop" has a z-index of 1040

Firefox ( v33.1) and IE(v9)
No z-index is being injected - so UI breaks apart - see below commment

"modal-scrollable" and ""modal-backdrop" are not receiving any "z-index" so clicking in the backdrop will not dismiss the modal - you have to click the "x" in the modal itself to close and dismiss.  With no z-indexes the "backdrop" now also sit behind other elements with z-index greater then 0.

In BS 3.2.0 or BS 3.1.1:
All Browsers declares the following z-indexes:
"modal-scrollable" has a z-index of 1060
"modal-backdrop" has a z-index of 1050

If anyone experience this issue and has a workaround I would love to know - or is this my own isolated issue?

thanks

**Comment by bhhaskin** [comment]
Looks like the modal-backdrop isn't working on v3.3.2 at all. the height is set to 0.

**Comment by jschr** [comment]
I've updated the BS3 patch file to support BS 3.3+ https://github.com/jschr/bootstrap-modal/commit/ad52cd59a4f113f1a626c193959a37c43a80c4c4
