### ISSUE TITLE
Is it possible to animate the modal closing?

### ISSUE THREAD

**Issue by TwentyOneSolutions** [jschr/bootstrap-modal#267]
I'm not sure if it's ok to open an issue for questions like this or if there is a mailing list or anything (I couldn't find).  If not, then please point me in the right direction.

I want to animate the closing of the modal so that it "zooms out" to a specific element on the page.  

So say I have an element and I can get its position via `var pos = $('#zoom-out-here').position()`, I want to set the modal box so that when it closes -- it animates to `size (0, 0)` at `position (pos.top, pos.left)`.

I use jQuery so the animation part should be rather simple, I'm not sure how to hook it up with bootstrap-modal though.

Is that possible?

TIA!

**Comment by jschr** [comment]
Here's an example that does the opposite (scales in): http://jsfiddle.net/jschr/B584D/ 

Should be pretty straight forward to adapt to trigger on close. The key is listening for the hide event:

```js
$modal.on('hide', function () {
  // apply transition
});
```

**Comment by TwentyOneSolutions** [comment]
Once again -- Thank you very much!

**Comment by TwentyOneSolutions** [comment]
Just because it wasn't as straightforward as I expected (the modal box closes immediately so the animation is not visible), I'm posting here the solution for the sake of others who might find this in the future:

    $modal.on('hide', function () {
        
        if (!$modal.isAnimating) {
            
            var $target = $('#zoomout-target');
            var pos = $target.position();    
            pos.top  -= $target.parent().scrollTop();
            pos.left -= $target.parent().scrollLeft();
        
            $modal.css({top: pos.top, left: pos.left, transform: 'scale(0.1, 0.1)'});
            
            $modal.isAnimating = true;
            setTimeout(function(){
                $modal.modal('hide');
                $modal.isAnimating = false;
            }, 500);
            return false;
        }
        
        $modal.css({top: '', left: '', transform: ''});
    });

and a fiddle:
http://jsfiddle.net/zt1d9cds/
