### ISSUE TITLE
Modal loading outside <form> issue

### ISSUE THREAD

**Issue by anupalusoft** [jschr/bootstrap-modal#271]
I want to open the modal default in to the div its placed so as to keep the Form submit button inside the form to not create issue while submitting. 
<code>
form start...
some input elements of form...
modal with submit button written <>
form end....
</code>

When i load it every time append to body thus making submit button scope out of form.
Please help how to fix it. I searched through already reported issues but didn't find any answer.

**Comment by jschr** [comment]
@anupalusoft the reason for moving the modal to body is to allow for stackable modals so there is no easy fix for this unfortunately. You would need to capture the modal submit with javascript and then trigger the original form submit.
