### ISSUE TITLE
Demo page doesn't works

### ISSUE THREAD

**Issue by Invis1ble** [jschr/bootstrap-modal#276]
Hello. Just for information. [The demo page](https://jschr.github.io/bootstrap-modal/) doesn't works at least in Chrome 43 due to security reasons. In browser console:
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure stylesheet 'http://getbootstrap.com/2.3.2/assets/css/bootstrap.css'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure stylesheet 'http://getbootstrap.com/2.3.2/assets/js/google-code-prettify/prettify.css'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure stylesheet 'http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=jschr&repo=bootstrap-modal&type=watch&count=true'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure resource 'http://ghbtns.com/github-btn.html?user=jschr&repo=bootstrap-modal&type=fork&count=true'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/KwPYo.jpg'. This content should also be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/KwPYo.jpg'. This content should also be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure image 'http://i.imgur.com/KwPYo.jpg'. This content should also be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure script 'http://getbootstrap.com/2.3.2/assets/js/google-code-prettify/prettify.js'. This request has been blocked; the content must be served over HTTPS.
> Mixed Content: The page at 'https://jschr.github.io/bootstrap-modal/' was loaded over HTTPS, but requested an insecure script 'http://getbootstrap.com/2.3.2/assets/js/bootstrap.js'. This request has been blocked; the content must be served over HTTPS.
> Uncaught ReferenceError: jQuery is not defined
> Uncaught TypeError: Cannot read property 'fn' of undefined
> Uncaught ReferenceError: $ is not defined
> Uncaught ReferenceError: $ is not defined
> Uncaught ReferenceError: $ is not defined

**Comment by Invis1ble** [comment]
PS. In Firefox 38 the same errors.

**Comment by Invis1ble** [comment]
Ah, sorry. I though that GitHub server forcibly redirects me on https version from http, but it was the HTTPS Everywhere plugin.

**Comment by jschr** [comment]
I think for the most part those resources support https so I should probably change that. Thanks for pointing it out
