### ISSUE TITLE
Incompatible with Boostrap 4?

### ISSUE THREAD

**Issue by emage** [jschr/bootstrap-modal#294]
I am upgrading my site to test with the Boostrap v4.0.0-alpha.6 and this plugin no longer work.  Will this plugin also be updated to support the upcoming release of BS4?

thanks,

**Comment by jschr** [comment]
If it's as simple as a css patch file like [bootstrap-modal-bs3patch.css](https://github.com/jschr/bootstrap-modal/blob/master/css/bootstrap-modal-bs3patch.css) I'd gladly accept a PR for it!

**Comment by jschr** [comment]
Side question, is there still a strong use case to use this plugin with BS4? The plugin was originally made for BS2 and there's been lots of improvements to the default modal since. 

Asking as someone who's been out of touch with bootstrap for a couple years now.

**Comment by maijianhu** [comment]
> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

http://v4-alpha.getbootstrap.com/components/modal/

**Comment by emage** [comment]
I was able to make it work with BS4 by changing the class name from "in" to "show" in both CSS and JS.
