### ISSUE TITLE
Body width increases when modal is opened

### ISSUE THREAD

**Issue by pomber** [jschr/bootstrap-modal#64]
When the modal is open, it applies the "modal-open" class to the body tag. The "overflow:hidden" style makes the body width to increase. 
If you have some horizontal centered content it moves a bit to the right, and back to the left when you close the modal.
I tried it in the demo page and the same happened. 
Is there any way to avoid this?

Only tested in Chrome.

**Comment by rogerionunes** [comment]
@jasonozias thx! NICE! :D

**Comment by NaikDeepak** [comment]
@jasonozias Thanks, finally something that really hat works!

**Comment by ianmartorell** [comment]
@jasonozias thanks!

**Comment by teleyinex** [comment]
@jasonozias thanks! It works here too!

**Comment by sahillamba** [comment]
@jasonozias :Thanks.Works for me too.

**Comment by marekjm** [comment]
@jasonozias Thank you! Works for me!

**Comment by adrianescat** [comment]
@jasonozias thats the solution. ty

**Comment by DurjoySaha** [comment]
many many thnx Mr. jschr And Pomber

**Comment by maxouni** [comment]
js simple solution:

customize bootstrap modal.js

hide: function (e) {
//add 
manager.$element.width(manager.$element.width());
//before string:
manager.appendModal(this);


hide: function (e) {
//add
jQuery('body').attr('style', '');

hard, but working!!!

**Comment by RafaPolit** [comment]
Thanks for the feedback!  I am trying @jasonozias solution, and it works on iOS.  But introduces dual-scrolls when the page has its own scroll and the modal requires a vertical scroll as well.

Have you guys figured out a solution for that issue? Is it happening to anyone else? Thanks,

Best regards,
Rafa.

**Comment by JViola** [comment]
padding-right: 0 !important is THE solution! Thx @jasonozias

**Comment by jmuheim** [comment]
:+1: @jasonozias

**Comment by DannyFeliz** [comment]
Thank you @jasonozias  :+1:

**Comment by theyuv** [comment]
@RafaPolit This happens to me as well. 
When desktop browser is not maximized, I have 2 scrollbars on the right of the page.

**Comment by RafaPolit** [comment]
@theyuv,

This solution worked for me without the double scroll, at least for the time being:
´´´

**Comment by theyuv** [comment]
@RafaPolit Thanks.
There's also this:
https://bugs.webkit.org/show_bug.cgi?format=multiple&id=152803
Although I'm not quite sure what it's saying.

**Comment by RafaPolit** [comment]
It´s apparently saying they have fixed the bug on a future release and we can remove this 'fixes' whenever the update comes forward to the public.

**Comment by koreguy** [comment]
The issue still persist until now in the latest chrome! 
Thanks @ghost for providing a working solution!

**Comment by joangavelan** [comment]
It took me a while to figure it out, but the problem is simply because the vertical scrollbar appears with a certain body height, before the modal (in my case a filterable product gallery) the body was not high enough for the vertical scrollbar to appear, but once it is and the scrollbar appears, it causes the content to be pushed to the left.

I solved this by leaving the vertical scrollbar always visible `body {overflow-y: scroll;}`

 or with `overflow: overlay` (not supported by all browsers).
